unbind = SUPER, B
bindd = SUPER, B, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
unbind = SUPER, T
bindd = SUPER, T, Kitty, exec, omarchy-launch-or-focus ^kitty$ "uwsm-app -- kitty"
unbind = SUPER, A
bindd = SUPER, A, Chrome, exec, omarchy-launch-or-focus ^google-chrome$ "uwsm-app -- google-chrome-stable"
unbind = SUPER, G
bindd = SUPER, G, Gemini, exec, omarchy-launch-or-focus-webapp Gemini "https://gemini.google.com"
# unbind = SUPER, G
# bindd = SUPER, G, ChatGPT, exec, omarchy-launch-or-focus-webapp ChatGPT "https://chatgpt.com"
unbind = SUPER, N
bindd = SUPER, N, Notion, exec, omarchy-launch-or-focus-webapp Notion "https://www.notion.so/junghochoi/Home-Page-2-0-18af38c876e7806eae3ee51d732df329"


unbind = SUPER, J
unbind = SUPER, K

bindd = SUPER, H, Move focus left, movefocus, l
bindd = SUPER, L, Move focus right, movefocus, r
bindd = SUPER, K, Move focus up, movefocus, u
bindd = SUPER, J, Move focus down, movefocus, d


bindd = SUPER ALT, H, Move Window to left, movewindow, l
bindd = SUPER ALT, L, Move Window to right, movewindow, r
bindd = SUPER ALT, K, Move Window to up, movewindow, u
bindd = SUPER ALT, J, Move Window to down, movewindow, d

bindd = SUPER CTRL, H, Swap Window to left, swapwindow, l
bindd = SUPER CTRL, L, Swap Window to right, swapwindow, r
bindd = SUPER CTRL, K, Swap Window to up, swapwindow, u
bindd = SUPER CTRL, J, Swap Window to down,swapwindow, d

# SUPER + SHIFT + WORKSPACE_NUMBER = Move window to that workspace number

# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu


# Application bindings
# bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
# bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
# bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser

# bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
# bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
# bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
# bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
# bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
# bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
# bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
# bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
# bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
# bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
# bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
# bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"
# bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
# bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
# bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
# bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
# bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
# bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menuo

