#h workspace = 1, kitty
# workspace = 2, google-chrome
# workspace = 3, obsidian
# workspace = 3, chrome-www.notion.so__junghochoi_Home-Page-2-0-18af38c876e7806eae3ee51d732df329-Default 


# windowrule = workspace 2, ^google-chrome$
# windowrule = workspace 2, google-chrome


windowrulev2 = workspace 1, class:kitty
windowrulev2 = workspace 2, class:google-chrome

windowrulev2 = workspace 3, class:^(.*)obsidian(.*)$
windowrulev2 = workspace 3, class:^chrome-www\.notion\.so__junghochoi_Home-Page-2-0-18af38c876e7806eae3ee51d732df329-Default$

bind = ALT, j, movecurrentworkspacetomonitor, -1
bind = ALT, k, movecurrentworkspacetomonitor, +1
